name: run-cmake
description: 'GitHub action to run CMake'
author: flagarde

inputs:
  source_dir:
    description: 'Path to root directory of the CMake project to build.'
    required: false
    default: ''
  binary_dir:
    description: 'Path to directory which CMake will use as the root of build directory.'
    required: false
    default: './build'
  initial_cache:
    description: 'Pre-load a script to populate the cache.'
    required: false
    default: './build'
  variables_before_initial_cache:
    description: 'Variable to set before loading the cache provided by "initial_cache"'
    required: false
    default: './build'


  generator:
    description: 'Generator to use (Unix Makefiles on Linux and macOS, NMake Makefiles in Windows)'
    required: false
    default: ''
  toolset:
    description: 'Toolset specification for the generator, if supported.'
    required: false
    default: ''
  install_prefix:
    description: 'Specify the installation directory, used by the CMAKE_INSTALL_PREFIX variable'
    required: false
    default: ''

runs:
  using: 'node20'
  main: 'dist/index.js'

branding:
  icon: 'settings'
  color: 'green'
