name: run-cmake
description: 'GitHub action to run CMake'
author: flagarde

inputs:
  # General options:
  mode:
    description: 'Mode in which CMake is running : configure, build, install, all'
    required: false
    default: 'configure'
  binary_dir:
    description: 'Path to directory which CMake will use as the root of build directory.'
    required: false
    default: '../build'
  
  # Configure mode options:
  source_dir:
    description: 'Path to root directory of the CMake project to build.'
    required: false
    default: ''
  initial_cache:
    description: 'Pre-load a script to populate the cache.'
    required: false
    default: ''
  variables:
    description: 'Variable to set'
    required: false
    default: ''
  remove_variables:
    description: 'Remove matching entries from CMake CACHE.'
    required: false
    default: ''
  generator:
    description: 'Generator to use (Unix Makefiles on Linux and macOS, NMake Makefiles in Windows)'
    required: false
    default: ''
  toolset:
    description: 'Toolset specification for the generator, if supported.'
    required: false
    default: ''
  platform:
    description: 'Specify platform name if supported by generator.'
    required: false
    default: ''
  toolchain:
    description: 'Specify the cross compiling toolchain file.'
    required: false
    default: ''
  install_prefix:
    description: 'Specify the installation directory, used by the CMAKE_INSTALL_PREFIX variable'
    required: false
    default: '../install'
  configure_warnings:
    description: 'Enable warnings. Choice is : none, deprecated, warning, developer'
    required: false
    default: ''
  configure_warnings_as_errors:
    description: 'Enable warnings as errors. Choice is : none, deprecated, warning, developer'
    required: false
    default: ''
  list_cache_variables:
    description: 'List cached variables. Choice is : none, cache, cache_help, advanced, advanced_help'
    required: false
    default: 'none'
  graphviz:
    description: 'Generate graphviz of dependencies, see CMakeGraphVizOptions for more'
    required: false
    default: ''
  log_level:
    description: 'Set the log level'
    required: false
    default: ''
  log_context:
    description: 'Enable the outputting context attached to each message.'
    required: false
    default: ''

  # Build mode options:
  parallel:
    description: "The maximum number of concurrent processes to use when building. If omitted the number of core available is used. (CMake 3.12+)"
    required: false
    default: ''
  build_targets:
    description: "Build targets provided instead of the default target. Multiple targets may be given, separated by spaces"
    required: false
    default: ''
  config:
    description: "For multi-configuration tools, choose configuration"
    required: false
    default: ''
  clean_first:
    description: "Build target clean first, then build"
    required: false
    default: ''
  resolve_package_references:
    description: 'Resolve remote package references from external package managers (e.g. NuGet) before build'
    required: false
    default: ''
  build_verbose:
    description: 'Enable verbose output - if supported - including the build commands to be executed'
    required: false
    default: ''

  # Install mode options:
  #config: 
  #  description: 'For multi-configuration generators, choose configuration'
  #  required: false
  #  default: ''
  component: 
    description: 'Component-based install. Only install component'
    required: false
    default: ''
  default_directory_permissions:
    description: 'Default directory install permissions'
    required: false
    default: ''
  override_install_prefix:
    description: 'Override the installation prefix'
    required: false
    default: ''
  strip:
    description: 'Strip before installing'
    required: false
    default: 'false'
  install_verbose:
    description: 'Enable verbose output'
    required: false
    default: 'false'



runs:
  using: 'node20'
  main: 'dist/index.js'

branding:
  icon: 'settings'
  color: 'green'
