on:
  push:

jobs:
  test:
    runs-on: macos-latest
    name: test run-cmake
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: run-cmake
        uses: ./
        id: hello