name: msys2

defaults:
  run:
    shell: msys2 {0}

on:
  push:
    paths-ignore:
      - '.github/workflows/**'
      - '!.github/workflows/msys2.yml'
  pull_request:
    paths-ignore:
      - '.github/workflows/**'
      - '!.github/workflows/msys2.yml'
  workflow_dispatch:

concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  msys2:
    runs-on: windows-latest
    name: ${{ matrix.system }} (${{ matrix.generator }})
    strategy:
      fail-fast: false
      matrix:
        system: [ msys, mingw64, ucrt64, clang64 ]
        generator: ['MSYS Makefiles','MinGW Makefiles','Unix Makefiles','Ninja', 'Ninja Multi-Config']
        exclude:
          - system: msys
            generator: 'MSYS Makefiles'
          - system: msys
            generator: 'MinGW Makefiles'

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Checkout tests repository
        uses: actions/checkout@v4
        with:
          repository: cmake-tools/runs.test
          path: tests

      - name: ⬇️ Setup MSYS2 (${{matrix.system}},${{matrix.generator}})
        uses: msys2/setup-msys2@v2
        with:
          msystem: ${{matrix.system}}
          path-type: minimal
          release: true
          update: true
          cache: true
          install: |
            cmake
            ninja
            make
          pacboy: |
            cmake:p
            ninja:p
            make:p
            ${{ (matrix.system=='clang64') && 'clang:p' || 'gcc:p' }}
      - name: ⚙️ run-cmake (configure)
        uses: ./
        id: 'configure'
        with:
          mode: configure
          generator: ${{matrix.generator}}
          install_prefix: '../install'
          binary_dir: '../build'
          source_dir: './tests'
          graphviz: ./dots/dependencies.dot
      - uses: actions/upload-artifact@v4
        with:
          name: dot_${{ github.workflow }}_${{ matrix.generator }}_${{ matrix.cmake_version }}
          path: ./dots/*
          if-no-files-found: warn
          retention-days: 90
          compression-level: 0
          overwrite: true
          include-hidden-files: false
      - name: 🛠️ run-cmake (build)
        uses: ./
        id: build
        with:
          mode: build
          config: Debug
          clean_first: true
          build_targets: |
            Main
          build_verbose: true

      - name: 📥 run-cmake (install)
        uses: ./
        id: install
        with:
          mode: install
          install_verbose: true
