on:
  push:

concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    name: CMake v3.${{ matrix.cmake_version }}
    strategy:
      fail-fast: false
      matrix:
        cmake_version: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install libidn11
        run: sudo apt-get update ; sudo apt-get install --no-install-recommends -y libidn12; ln -s  /usr/lib/x86_64-linux-gnu/libidn.so.12 /usr/lib/x86_64-linux-gnu/libidn.so.11
      - name: ⬇️ Setup CMake
        uses: lukka/get-cmake@latest
        with:
          cmakeVersion: ~3.${{ matrix.cmake_version }}
          ninjaVersion: ^1
      - name: run-cmake
        uses: ./
        id: hello
